name: 'QcmPlab setup action FORD'
description: 'Setup action for FORD'

inputs:

  python-version: 
    description: 'Python version input'
    required: false
    default: '3.9'

  config-name:
    description: 'config file path'
    required: false
    default: './docs.config'

runs:
  using: "composite" 
  steps:

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
      

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: debug
      run: |
        echo ${{runner.os}}
        echo contains(runner.os,'ubuntu')
      shell: bash

    - name: Install FORD & Generate DOCS
      if: contains(runner.os,'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install ford
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ford ${{ inputs.config-name }}
      shell: bash